name: settings_ui
description: Create native settings for Flutter app in minutes. Use single interfaces to build
version: 2.0.3
homepage: https://github.com/yako-dev/flutter-settings-ui

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0
  flutter_lints: ^2.0.1

flutter:
